#!/usr/bin/env python3
"""Generate (or verify) the audit v2 conformance vectors.

Expectations are hand-written per tamper type, never computed from the
verification result. Run without ``--check`` to (re)write the files;
with ``--check`` the generated bytes are compared against the files on
disk and any difference exits 1.
"""

from __future__ import annotations

import argparse
import base64
import copy
import hashlib
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(REPO))

from roe_guard.jcs import canonicalize

TEST_PRIVATE = bytes.fromhex(
    "9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60"
)
TEST_PUBLIC_HEX = "d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a"
TEST_KEY_ID = "sha256:21fe31dfa154a261626bf854046fd2271b7bed4b6abe45aa58877ef47f9721b9"

CHAIN_ID = "conformance-chain"
POLICY_SHA = hashlib.sha256(b"conformance-policy").hexdigest()

TIMESTAMPS = [
    "2026-10-01T10:00:00.000000Z",
    "2026-10-01T10:00:01.000000Z",
    "2026-10-01T10:00:02.000000Z",
]


def _sign(message: bytes) -> bytes:
    from cryptography.hazmat.primitives.asymmetric.ed25519 import (
        Ed25519PrivateKey,
    )

    return Ed25519PrivateKey.from_private_bytes(TEST_PRIVATE).sign(message)


def _make_record(seq: int, prev_hash: str, **overrides):
    record = {
        "v": 2,
        "seq": seq,
        "chain_id": CHAIN_ID,
        "timestamp": TIMESTAMPS[min(seq, len(TIMESTAMPS) - 1)],
        "engagement_id": "conf-eng",
        "policy_sha256": POLICY_SHA,
        "mode": "enforce",
        "agent_id": "spiffe://example.org/agent/a1",
        "target": f"10.20.3.{5 + seq}",
        "action_type": "recon",
        "decision": "ALLOW",
        "reason": "action type 'recon' allowed",
        "reason_code": "ACTION_ALLOWED",
        "metadata": {"i": seq},
        "prev_hash": prev_hash,
    }
    record.update({k: v for k, v in overrides.items() if k != "entry_hash"})
    record["entry_hash"] = hashlib.sha256(
        canonicalize({k: v for k, v in record.items() if k != "entry_hash"})
    ).hexdigest()
    record.update({k: v for k, v in overrides.items() if k == "entry_hash"})
    return record


def _make_v1_record(prev_hash: str, target: str):
    record = {
        "engagement_id": "conf-v1",
        "timestamp": "2026-08-10T12:00:00",
        "target": target,
        "action_type": "recon",
        "decision": "ALLOW",
        "reason": "action type 'recon' allowed",
        "prev_hash": prev_hash,
        "entry_hash": "",
    }
    record["entry_hash"] = hashlib.sha256(
        json.dumps(
            record, sort_keys=True, separators=(",", ":"), ensure_ascii=False
        ).encode()
    ).hexdigest()
    return record


def _make_checkpoint(seq: int, head_hash: str, **overrides):
    checkpoint = {
        "v": 2,
        "chain_id": CHAIN_ID,
        "seq": seq,
        "head_hash": head_hash,
        "timestamp": TIMESTAMPS[0],
        "key_id": TEST_KEY_ID,
    }
    checkpoint.update({k: v for k, v in overrides.items() if k != "sig"})
    signature = _sign(canonicalize(checkpoint))
    checkpoint["sig"] = base64.urlsafe_b64encode(signature).rstrip(b"=").decode("ascii")
    checkpoint.update({k: v for k, v in overrides.items() if k == "sig"})
    return checkpoint


def _valid_chain(n: int = 3):
    records = []
    prev = "0" * 64
    for seq in range(n):
        records.append(_make_record(seq, prev))
        prev = records[-1]["entry_hash"]
    return records


def build_cases() -> dict:
    cases = []
    public_keys = {TEST_KEY_ID: TEST_PUBLIC_HEX}

    valid = _valid_chain(3)
    cases.append(
        {
            "id": "v2-valid-basic",
            "description": "Three well-formed v2 records verify.",
            "chain": [canonicalize(r).decode() for r in valid],
            "checkpoints": None,
            "public_keys": None,
            "expected": {"valid": True, "broken_at_index": None, "reason_code": None},
        }
    )

    head = valid[-1]["entry_hash"]
    checkpoint = _make_checkpoint(2, head)
    cases.append(
        {
            "id": "v2-valid-checkpoint",
            "description": "A signed checkpoint at the chain head verifies.",
            "chain": [canonicalize(r).decode() for r in valid],
            "checkpoints": [canonicalize(checkpoint).decode()],
            "public_keys": public_keys,
            "expected": {"valid": True, "broken_at_index": None, "reason_code": None},
        }
    )

    v1a = _make_v1_record("0" * 64, "10.20.3.5")
    v1b = _make_v1_record(v1a["entry_hash"], "10.20.3.6")
    mixed_v2 = []
    prev = v1b["entry_hash"]
    for seq in (2, 3):
        mixed_v2.append(_make_record(seq, prev))
        prev = mixed_v2[-1]["entry_hash"]
    cases.append(
        {
            "id": "mixed-v1-v2-valid",
            "description": "Two v1 lines followed by two v2 lines verify.",
            "chain": [canonicalize(r).decode() for r in [v1a, v1b] + mixed_v2],
            "checkpoints": None,
            "public_keys": None,
            "expected": {"valid": True, "broken_at_index": None, "reason_code": None},
        }
    )

    # --- tamper cases (expectations hand-written per tamper type) -------

    downgraded = copy.deepcopy(valid)
    downgraded.append(_make_v1_record(valid[-1]["entry_hash"], "10.20.3.8"))
    cases.append(
        {
            "id": "v2-version-downgrade",
            "description": "A v1 line after a v2 line is a version downgrade.",
            "chain": [canonicalize(r).decode() for r in downgraded],
            "checkpoints": None,
            "public_keys": None,
            "expected": {
                "valid": False,
                "broken_at_index": 3,
                "reason_code": "VERSION_DOWNGRADE",
            },
        }
    )

    extra = copy.deepcopy(valid)
    record = copy.deepcopy(extra[1])
    record["extra"] = 1
    record["entry_hash"] = hashlib.sha256(
        canonicalize({k: v for k, v in record.items() if k != "entry_hash"})
    ).hexdigest()
    extra[1] = record
    cases.append(
        {
            "id": "v2-unknown-field",
            "description": "An extra field re-hashed into place is UNKNOWN_FIELD.",
            "chain": [canonicalize(r).decode() for r in extra],
            "checkpoints": None,
            "public_keys": None,
            "expected": {
                "valid": False,
                "broken_at_index": 1,
                "reason_code": "UNKNOWN_FIELD",
            },
        }
    )

    tampered = copy.deepcopy(valid)
    record = copy.deepcopy(tampered[2])
    record["reason"] = "tampered"
    tampered[2] = record
    cases.append(
        {
            "id": "v2-entry-hash-mismatch",
            "description": "Changing the reason without re-hashing is ENTRY_HASH_MISMATCH at that line.",
            "chain": [canonicalize(r).decode() for r in tampered],
            "checkpoints": None,
            "public_keys": None,
            "expected": {
                "valid": False,
                "broken_at_index": 2,
                "reason_code": "ENTRY_HASH_MISMATCH",
            },
        }
    )

    seqskip = copy.deepcopy(valid)
    record = copy.deepcopy(seqskip[1])
    record["seq"] = 5
    record["entry_hash"] = hashlib.sha256(
        canonicalize({k: v for k, v in record.items() if k != "entry_hash"})
    ).hexdigest()
    seqskip[1] = record
    cases.append(
        {
            "id": "v2-seq-mismatch",
            "description": "A skipped seq is SEQ_MISMATCH.",
            "chain": [canonicalize(r).decode() for r in seqskip],
            "checkpoints": None,
            "public_keys": None,
            "expected": {
                "valid": False,
                "broken_at_index": 1,
                "reason_code": "SEQ_MISMATCH",
            },
        }
    )

    tsoffset = copy.deepcopy(valid)
    record = copy.deepcopy(tsoffset[0])
    record["timestamp"] = "2026-10-01T10:00:00+00:00"
    record["entry_hash"] = hashlib.sha256(
        canonicalize({k: v for k, v in record.items() if k != "entry_hash"})
    ).hexdigest()
    tsoffset[0] = record
    cases.append(
        {
            "id": "v2-timestamp-offset-form",
            "description": "A +00:00 timestamp is TIMESTAMP_FORMAT (raw RFC 3339 UTC only).",
            "chain": [canonicalize(r).decode() for r in tsoffset],
            "checkpoints": None,
            "public_keys": None,
            "expected": {
                "valid": False,
                "broken_at_index": 0,
                "reason_code": "TIMESTAMP_FORMAT",
            },
        }
    )

    v3 = copy.deepcopy(valid)
    record = copy.deepcopy(v3[0])
    record["v"] = 3
    record["entry_hash"] = hashlib.sha256(
        canonicalize({k: v for k, v in record.items() if k != "entry_hash"})
    ).hexdigest()
    v3[0] = record
    cases.append(
        {
            "id": "v2-unknown-version",
            "description": "v: 3 is UNKNOWN_VERSION.",
            "chain": [canonicalize(r).decode() for r in v3],
            "checkpoints": None,
            "public_keys": None,
            "expected": {
                "valid": False,
                "broken_at_index": 0,
                "reason_code": "UNKNOWN_VERSION",
            },
        }
    )

    truncated = [canonicalize(r).decode() for r in valid[:2]]
    trunc_ckpt = _make_checkpoint(2, valid[-1]["entry_hash"])
    cases.append(
        {
            "id": "v2-chain-truncated",
            "description": "A checkpoint past the truncated head detects the cut.",
            "chain": truncated,
            "checkpoints": [canonicalize(trunc_ckpt).decode()],
            "public_keys": public_keys,
            "expected": {
                "valid": False,
                "broken_at_index": 2,
                "reason_code": "CHAIN_TRUNCATED",
            },
        }
    )

    bad_sig = _make_checkpoint(2, valid[-1]["entry_hash"], sig="A" * 86)
    cases.append(
        {
            "id": "v2-checkpoint-signature-invalid",
            "description": "A forged checkpoint signature is rejected.",
            "chain": [canonicalize(r).decode() for r in valid],
            "checkpoints": [canonicalize(bad_sig).decode()],
            "public_keys": public_keys,
            "expected": {
                "valid": False,
                "broken_at_index": 2,
                "reason_code": "CHECKPOINT_SIGNATURE_INVALID",
            },
        }
    )

    unknown_key = _make_checkpoint(2, valid[-1]["entry_hash"])
    cases.append(
        {
            "id": "v2-checkpoint-key-unknown",
            "description": "A checkpoint signed by an unknown key is rejected.",
            "chain": [canonicalize(r).decode() for r in valid],
            "checkpoints": [canonicalize(unknown_key).decode()],
            "public_keys": None,
            "expected": {
                "valid": False,
                "broken_at_index": 2,
                "reason_code": "CHECKPOINT_KEY_UNKNOWN",
            },
        }
    )

    wrong_head = _make_checkpoint(2, "b" * 64)
    cases.append(
        {
            "id": "v2-checkpoint-head-mismatch",
            "description": "A checkpoint naming a foreign head is CHECKPOINT_HEAD_MISMATCH.",
            "chain": [canonicalize(r).decode() for r in valid],
            "checkpoints": [canonicalize(wrong_head).decode()],
            "public_keys": public_keys,
            "expected": {
                "valid": False,
                "broken_at_index": 2,
                "reason_code": "CHECKPOINT_HEAD_MISMATCH",
            },
        }
    )

    other_chain = copy.deepcopy(valid)
    record = copy.deepcopy(other_chain[1])
    record["chain_id"] = "other-chain"
    record["entry_hash"] = hashlib.sha256(
        canonicalize({k: v for k, v in record.items() if k != "entry_hash"})
    ).hexdigest()
    other_chain[1] = record
    cases.append(
        {
            "id": "v2-chain-id-mismatch",
            "description": "A foreign chain_id is CHAIN_ID_MISMATCH.",
            "chain": [canonicalize(r).decode() for r in other_chain],
            "checkpoints": None,
            "public_keys": None,
            "expected": {
                "valid": False,
                "broken_at_index": 1,
                "reason_code": "CHAIN_ID_MISMATCH",
            },
        }
    )

    prevbad = copy.deepcopy(valid)
    record = copy.deepcopy(prevbad[2])
    record["prev_hash"] = "c" * 64
    record["entry_hash"] = hashlib.sha256(
        canonicalize({k: v for k, v in record.items() if k != "entry_hash"})
    ).hexdigest()
    prevbad[2] = record
    cases.append(
        {
            "id": "v2-prev-hash-mismatch",
            "description": "A broken link is PREV_HASH_MISMATCH.",
            "chain": [canonicalize(r).decode() for r in prevbad],
            "checkpoints": None,
            "public_keys": None,
            "expected": {
                "valid": False,
                "broken_at_index": 2,
                "reason_code": "PREV_HASH_MISMATCH",
            },
        }
    )

    missing_key = copy.deepcopy(valid)
    record = copy.deepcopy(missing_key[1])
    record.pop("reason_code")
    record["entry_hash"] = hashlib.sha256(
        canonicalize({k: v for k, v in record.items() if k != "entry_hash"})
    ).hexdigest()
    missing_key[1] = record
    cases.append(
        {
            "id": "v2-malformed-missing-key",
            "description": "A missing key is MALFORMED.",
            "chain": [canonicalize(r).decode() for r in missing_key],
            "checkpoints": None,
            "public_keys": None,
            "expected": {
                "valid": False,
                "broken_at_index": 1,
                "reason_code": "MALFORMED",
            },
        }
    )

    dup_raw = json.dumps(valid[0], sort_keys=True)
    dup_line = dup_raw[:-1] + ',"seq":0}'
    cases.append(
        {
            "id": "v2-malformed-duplicate-key",
            "description": "A duplicated key is MALFORMED.",
            "chain": [dup_line] + [canonicalize(r).decode() for r in valid[1:]],
            "checkpoints": None,
            "public_keys": None,
            "expected": {
                "valid": False,
                "broken_at_index": 0,
                "reason_code": "MALFORMED",
            },
        }
    )

    cases.append(
        {
            "id": "v2-invalid-json",
            "description": "A non-JSON line is INVALID_JSON.",
            "chain": ["{not json"],
            "checkpoints": None,
            "public_keys": None,
            "expected": {
                "valid": False,
                "broken_at_index": 0,
                "reason_code": "INVALID_JSON",
            },
        }
    )

    return {
        "format": 1,
        "suite": "audit-v2",
        "cases": cases,
    }


def build_jcs_cases() -> dict:
    rfc_object = {
        "€": "Euro Sign",
        "\r": "Carriage Return",
        "דּ": "Hebrew Letter Dalet With Dagesh",
        "1": "One",
        "\U0001f600": "Emoji: Grinning Face",
        "\u0080": "Control",
        "ö": "Latin Small Letter O With Diaeresis",
    }

    def canon_hex(value) -> str:
        return canonicalize(value).hex()

    return {
        "format": 1,
        "suite": "jcs",
        "cases": [
            {
                "id": "jcs-rfc-ordering",
                "description": "RFC 8785 §3.2.3 UTF-16 key ordering example.",
                "input_json": json.dumps(rfc_object, ensure_ascii=False),
                "expected_hex": canon_hex(rfc_object),
            },
            {
                "id": "jcs-control-escape",
                "description": "Control characters use lowercase \\u00xx escapes.",
                "input_json": json.dumps({"k": '"\\'}, ensure_ascii=False),
                "expected_hex": canon_hex({"k": '"\\'}),
            },
            {
                "id": "jcs-quote-backslash",
                "description": "Quote and backslash escaping.",
                "input_json": json.dumps({"k": '"\\'}, ensure_ascii=False),
                "expected_hex": canon_hex({"k": '"\\'}),
            },
            {
                "id": "jcs-literals",
                "description": "true/false/null serialization.",
                "input_json": '{"a":true,"b":false,"c":null}',
                "expected_hex": canon_hex({"a": True, "b": False, "c": None}),
            },
            {
                "id": "jcs-array-order",
                "description": "Array order is preserved.",
                "input_json": '{"a":[3,1,2]}',
                "expected_hex": canon_hex({"a": [3, 1, 2]}),
            },
            {
                "id": "jcs-nested",
                "description": "Nested objects are ordered at every level.",
                "input_json": json.dumps(
                    {"b": {"z": 1, "a": 2}, "a": 3}, ensure_ascii=False
                ),
                "expected_hex": canon_hex({"b": {"a": 2, "z": 1}, "a": 3}),
            },
            {
                "id": "jcs-error-float",
                "description": "Floats are unsupported.",
                "input_json": '{"x":1.5}',
                "expected_error": "UNSUPPORTED_NUMBER",
            },
            {
                "id": "jcs-error-surrogate",
                "description": "Lone surrogates are invalid.",
                "input_json": '{"x":"\\ud800"}',
                "expected_error": "LONE_SURROGATE",
            },
        ],
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="compare generated bytes with the files"
    )
    args = parser.parse_args()

    audit_dir = REPO / "conformance" / "audit"
    jcs_dir = REPO / "conformance" / "jcs"
    audit_file = audit_dir / "cases.json"
    jcs_file = jcs_dir / "cases.json"

    audit_bytes = (
        json.dumps(build_cases(), indent=2, ensure_ascii=False) + "\n"
    ).encode()
    jcs_bytes = (
        json.dumps(build_jcs_cases(), indent=2, ensure_ascii=False) + "\n"
    ).encode()

    if args.check:
        ok = True
        if audit_file.read_bytes() != audit_bytes:
            print(f"FAILED: {audit_file} differs")
            ok = False
        if jcs_file.read_bytes() != jcs_bytes:
            print(f"FAILED: {jcs_file} differs")
            ok = False
        return 0 if ok else 1

    audit_dir.mkdir(parents=True, exist_ok=True)
    jcs_dir.mkdir(parents=True, exist_ok=True)
    audit_file.write_bytes(audit_bytes)
    jcs_file.write_bytes(jcs_bytes)
    print(f"wrote {audit_file} ({len(build_cases()['cases'])} cases)")
    print(f"wrote {jcs_file} ({len(build_jcs_cases()['cases'])} cases)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
