#!/usr/bin/env python3
"""Generate (or verify) the audit v2 conformance vectors.

Expectations are hand-written per tamper type, never computed from the
verification result. Run without ``--check`` to (re)write the files;
with ``--check`` the generated bytes are compared against the files on
disk and any difference exits 1.
"""

from __future__ import annotations

import argparse
import base64
import copy
import hashlib
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(REPO))

from roe_guard.jcs import canonicalize

TEST_PRIVATE = bytes.fromhex(
    "9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60"
)
TEST_PUBLIC_HEX = "d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a"
TEST_KEY_ID = "sha256:21fe31dfa154a261626bf854046fd2271b7bed4b6abe45aa58877ef47f9721b9"

CHAIN_ID = "conformance-chain"
POLICY_SHA = hashlib.sha256(b"conformance-policy").hexdigest()

TIMESTAMPS = [
    "2026-10-01T10:00:00.000000Z",
    "2026-10-01T10:00:01.000000Z",
    "2026-10-01T10:00:02.000000Z",
]


def _sign(message: bytes) -> bytes:
    from cryptography.hazmat.primitives.asymmetric.ed25519 import (
        Ed25519PrivateKey,
    )

    return Ed25519PrivateKey.from_private_bytes(TEST_PRIVATE).sign(message)


def _make_record(seq: int, prev_hash: str, **overrides):
    record = {
        "v": 2,
        "seq": seq,
        "chain_id": CHAIN_ID,
        "timestamp": TIMESTAMPS[min(seq, len(TIMESTAMPS) - 1)],
        "engagement_id": "conf-eng",
        "policy_sha256": POLICY_SHA,
        "mode": "enforce",
        "agent_id": "spiffe://example.org/agent/a1",
        "target": f"10.20.3.{5 + seq}",
        "action_type": "recon",
        "decision": "ALLOW",
        "reason": "action type 'recon' allowed",
        "reason_code": "ACTION_ALLOWED",
        "metadata": {"i": seq},
        "prev_hash": prev_hash,
    }
    record.update({k: v for k, v in overrides.items() if k != "entry_hash"})
    record["entry_hash"] = hashlib.sha256(
        canonicalize({k: v for k, v in record.items() if k != "entry_hash"})
    ).hexdigest()
    record.update({k: v for k, v in overrides.items() if k == "entry_hash"})
    return record


def _make_v1_record(prev_hash: str, target: str):
    record = {
        "engagement_id": "conf-v1",
        "timestamp": "2026-08-10T12:00:00",
        "target": target,
        "action_type": "recon",
        "decision": "ALLOW",
        "reason": "action type 'recon' allowed",
        "prev_hash": prev_hash,
        "entry_hash": "",
    }
    record["entry_hash"] = hashlib.sha256(
        json.dumps(
            record, sort_keys=True, separators=(",", ":"), ensure_ascii=False
        ).encode()
    ).hexdigest()
    return record


def _make_checkpoint(seq: int, head_hash: str, **overrides):
    checkpoint = {
        "v": 2,
        "chain_id": CHAIN_ID,
        "seq": seq,
        "head_hash": head_hash,
        "timestamp": TIMESTAMPS[0],
        "key_id": TEST_KEY_ID,
    }
    checkpoint.update({k: v for k, v in overrides.items() if k != "sig"})
    signature = _sign(canonicalize(checkpoint))
    checkpoint["sig"] = base64.urlsafe_b64encode(signature).rstrip(b"=").decode("ascii")
    checkpoint.update({k: v for k, v in overrides.items() if k == "sig"})
    return checkpoint


def _valid_chain(n: int = 3):
    records = []
    prev = "0" * 64
    for seq in range(n):
        records.append(_make_record(seq, prev))
        prev = records[-1]["entry_hash"]
    return records


def build_cases() -> dict:
    cases = []
    public_keys = {TEST_KEY_ID: TEST_PUBLIC_HEX}

    valid = _valid_chain(3)
    cases.append(
        {
            "id": "v2-valid-basic",
            "description": "Three well-formed v2 records verify.",
            "chain": [canonicalize(r).decode() for r in valid],
            "checkpoints": None,
            "public_keys": None,
            "expected": {"valid": True, "broken_at_index": None, "reason_code": None},
        }
    )

    head = valid[-1]["entry_hash"]
    checkpoint = _make_checkpoint(2, head)
    cases.append(
        {
            "id": "v2-valid-checkpoint",
            "description": "A signed checkpoint at the chain head verifies.",
            "chain": [canonicalize(r).decode() for r in valid],
            "checkpoints": [canonicalize(checkpoint).decode()],
            "public_keys": public_keys,
            "expected": {"valid": True, "broken_at_index": None, "reason_code": None},
        }
    )

    v1a = _make_v1_record("0" * 64, "10.20.3.5")
    v1b = _make_v1_record(v1a["entry_hash"], "10.20.3.6")
    mixed_v2 = []
    prev = v1b["entry_hash"]
    for seq in (2, 3):
        mixed_v2.append(_make_record(seq, prev))
        prev = mixed_v2[-1]["entry_hash"]
    cases.append(
        {
            "id": "mixed-v1-v2-valid",
            "description": "Two v1 lines followed by two v2 lines verify.",
            "chain": [canonicalize(r).decode() for r in [v1a, v1b] + mixed_v2],
            "checkpoints": None,
            "public_keys": None,
            "expected": {"valid": True, "broken_at_index": None, "reason_code": None},
        }
    )

    # --- tamper cases (expectations hand-written per tamper type) -------

    downgraded = copy.deepcopy(valid)
    downgraded.append(_make_v1_record(valid[-1]["entry_hash"], "10.20.3.8"))
    cases.append(
        {
            "id": "v2-version-downgrade",
            "description": "A v1 line after a v2 line is a version downgrade.",
            "chain": [canonicalize(r).decode() for r in downgraded],
            "checkpoints": None,
            "public_keys": None,
            "expected": {
                "valid": False,
                "broken_at_index": 3,
                "reason_code": "VERSION_DOWNGRADE",
            },
        }
    )

    extra = copy.deepcopy(valid)
    record = copy.deepcopy(extra[1])
    record["extra"] = 1
    record["entry_hash"] = hashlib.sha256(
        canonicalize({k: v for k, v in record.items() if k != "entry_hash"})
    ).hexdigest()
    extra[1] = record
    cases.append(
        {
            "id": "v2-unknown-field",
            "description": "An extra field re-hashed into place is UNKNOWN_FIELD.",
            "chain": [canonicalize(r).decode() for r in extra],
            "checkpoints": None,
            "public_keys": None,
            "expected": {
                "valid": False,
                "broken_at_index": 1,
                "reason_code": "UNKNOWN_FIELD",
            },
        }
    )

    tampered = copy.deepcopy(valid)
    record = copy.deepcopy(tampered[2])
    record["reason"] = "tampered"
    tampered[2] = record
    cases.append(
        {
            "id": "v2-entry-hash-mismatch",
            "description": "Changing the reason without re-hashing is ENTRY_HASH_MISMATCH at that line.",
            "chain": [canonicalize(r).decode() for r in tampered],
            "checkpoints": None,
            "public_keys": None,
            "expected": {
                "valid": False,
                "broken_at_index": 2,
                "reason_code": "ENTRY_HASH_MISMATCH",
            },
        }
    )

    seqskip = copy.deepcopy(valid)
    record = copy.deepcopy(seqskip[1])
    record["seq"] = 5
    record["entry_hash"] = hashlib.sha256(
        canonicalize({k: v for k, v in record.items() if k != "entry_hash"})
    ).hexdigest()
    seqskip[1] = record
    cases.append(
        {
            "id": "v2-seq-mismatch",
            "description": "A skipped seq is SEQ_MISMATCH.",
            "chain": [canonicalize(r).decode() for r in seqskip],
            "checkpoints": None,
            "public_keys": None,
            "expected": {
                "valid": False,
                "broken_at_index": 1,
                "reason_code": "SEQ_MISMATCH",
            },
        }
    )

    tsoffset = copy.deepcopy(valid)
    record = copy.deepcopy(tsoffset[0])
    record["timestamp"] = "2026-10-01T10:00:00+00:00"
    record["entry_hash"] = hashlib.sha256(
        canonicalize({k: v for k, v in record.items() if k != "entry_hash"})
    ).hexdigest()
    tsoffset[0] = record
    cases.append(
        {
            "id": "v2-timestamp-offset-form",
            "description": "A +00:00 timestamp is TIMESTAMP_FORMAT (raw RFC 3339 UTC only).",
            "chain": [canonicalize(r).decode() for r in tsoffset],
            "checkpoints": None,
            "public_keys": None,
            "expected": {
                "valid": False,
                "broken_at_index": 0,
                "reason_code": "TIMESTAMP_FORMAT",
            },
        }
    )

    v3 = copy.deepcopy(valid)
    record = copy.deepcopy(v3[0])
    record["v"] = 3
    record["entry_hash"] = hashlib.sha256(
        canonicalize({k: v for k, v in record.items() if k != "entry_hash"})
    ).hexdigest()
    v3[0] = record
    cases.append(
        {
            "id": "v2-unknown-version",
            "description": "v: 3 is UNKNOWN_VERSION.",
            "chain": [canonicalize(r).decode() for r in v3],
            "checkpoints": None,
            "public_keys": None,
            "expected": {
                "valid": False,
                "broken_at_index": 0,
                "reason_code": "UNKNOWN_VERSION",
            },
        }
    )

    truncated = [canonicalize(r).decode() for r in valid[:2]]
    trunc_ckpt = _make_checkpoint(2, valid[-1]["entry_hash"])
    cases.append(
        {
            "id": "v2-chain-truncated",
            "description": "A checkpoint past the truncated head detects the cut.",
            "chain": truncated,
            "checkpoints": [canonicalize(trunc_ckpt).decode()],
            "public_keys": public_keys,
            "expected": {
                "valid": False,
                "broken_at_index": 2,
                "reason_code": "CHAIN_TRUNCATED",
            },
        }
    )

    bad_sig = _make_checkpoint(2, valid[-1]["entry_hash"], sig="A" * 86)
    cases.append(
        {
            "id": "v2-checkpoint-signature-invalid",
            "description": "A forged checkpoint signature is rejected.",
            "chain": [canonicalize(r).decode() for r in valid],
            "checkpoints": [canonicalize(bad_sig).decode()],
            "public_keys": public_keys,
            "expected": {
                "valid": False,
                "broken_at_index": 2,
                "reason_code": "CHECKPOINT_SIGNATURE_INVALID",
            },
        }
    )

    unknown_key = _make_checkpoint(2, valid[-1]["entry_hash"])
    cases.append(
        {
            "id": "v2-checkpoint-key-unknown",
            "description": "A checkpoint signed by an unknown key is rejected.",
            "chain": [canonicalize(r).decode() for r in valid],
            "checkpoints": [canonicalize(unknown_key).decode()],
            "public_keys": None,
            "expected": {
                "valid": False,
                "broken_at_index": 2,
                "reason_code": "CHECKPOINT_KEY_UNKNOWN",
            },
        }
    )

    wrong_head = _make_checkpoint(2, "b" * 64)
    cases.append(
        {
            "id": "v2-checkpoint-head-mismatch",
            "description": "A checkpoint naming a foreign head is CHECKPOINT_HEAD_MISMATCH.",
            "chain": [canonicalize(r).decode() for r in valid],
            "checkpoints": [canonicalize(wrong_head).decode()],
            "public_keys": public_keys,
            "expected": {
                "valid": False,
                "broken_at_index": 2,
                "reason_code": "CHECKPOINT_HEAD_MISMATCH",
            },
        }
    )

    other_chain = copy.deepcopy(valid)
    record = copy.deepcopy(other_chain[1])
    record["chain_id"] = "other-chain"
    record["entry_hash"] = hashlib.sha256(
        canonicalize({k: v for k, v in record.items() if k != "entry_hash"})
    ).hexdigest()
    other_chain[1] = record
    cases.append(
        {
            "id": "v2-chain-id-mismatch",
            "description": "A foreign chain_id is CHAIN_ID_MISMATCH.",
            "chain": [canonicalize(r).decode() for r in other_chain],
            "checkpoints": None,
            "public_keys": None,
            "expected": {
                "valid": False,
                "broken_at_index": 1,
                "reason_code": "CHAIN_ID_MISMATCH",
            },
        }
    )

    prevbad = copy.deepcopy(valid)
    record = copy.deepcopy(prevbad[2])
    record["prev_hash"] = "c" * 64
    record["entry_hash"] = hashlib.sha256(
        canonicalize({k: v for k, v in record.items() if k != "entry_hash"})
    ).hexdigest()
    prevbad[2] = record
    cases.append(
        {
            "id": "v2-prev-hash-mismatch",
            "description": "A broken link is PREV_HASH_MISMATCH.",
            "chain": [canonicalize(r).decode() for r in prevbad],
            "checkpoints": None,
            "public_keys": None,
            "expected": {
                "valid": False,
                "broken_at_index": 2,
                "reason_code": "PREV_HASH_MISMATCH",
            },
        }
    )

    missing_key = copy.deepcopy(valid)
    record = copy.deepcopy(missing_key[1])
    record.pop("reason_code")
    record["entry_hash"] = hashlib.sha256(
        canonicalize({k: v for k, v in record.items() if k != "entry_hash"})
    ).hexdigest()
    missing_key[1] = record
    cases.append(
        {
            "id": "v2-malformed-missing-key",
            "description": "A missing key is MALFORMED.",
            "chain": [canonicalize(r).decode() for r in missing_key],
            "checkpoints": None,
            "public_keys": None,
            "expected": {
                "valid": False,
                "broken_at_index": 1,
                "reason_code": "MALFORMED",
            },
        }
    )

    dup_raw = json.dumps(valid[0], sort_keys=True)
    dup_line = dup_raw[:-1] + ',"seq":0}'
    cases.append(
        {
            "id": "v2-malformed-duplicate-key",
            "description": "A duplicated key is MALFORMED.",
            "chain": [dup_line] + [canonicalize(r).decode() for r in valid[1:]],
            "checkpoints": None,
            "public_keys": None,
            "expected": {
                "valid": False,
                "broken_at_index": 0,
                "reason_code": "MALFORMED",
            },
        }
    )

    cases.append(
        {
            "id": "v2-invalid-json",
            "description": "A non-JSON line is INVALID_JSON.",
            "chain": ["{not json"],
            "checkpoints": None,
            "public_keys": None,
            "expected": {
                "valid": False,
                "broken_at_index": 0,
                "reason_code": "INVALID_JSON",
            },
        }
    )

    # --- review round additions (expectations hand-written) ------------

    def lines(records):
        return [canonicalize(r).decode() for r in records]

    def add(case_id, description, chain, expected, checkpoints=None, keys=None):
        valid_case = expected is None
        cases.append(
            {
                "id": case_id,
                "description": description,
                "chain": chain,
                "checkpoints": checkpoints,
                "public_keys": keys,
                "expected": {
                    "valid": valid_case,
                    "broken_at_index": None if valid_case else expected[1],
                    "reason_code": None if valid_case else expected[0],
                },
            }
        )

    def rehashed(index, mutate, base=None):
        records = copy.deepcopy(base or valid)
        record = records[index]
        mutate(record)
        record["entry_hash"] = hashlib.sha256(
            canonicalize({k: v for k, v in record.items() if k != "entry_hash"})
        ).hexdigest()
        return records

    add(
        "v2-timestamp-trailing-newline",
        "A timestamp ending in \\n is TIMESTAMP_FORMAT (fullmatch, not search).",
        lines(rehashed(0, lambda r: r.update(timestamp=TIMESTAMPS[0] + "\n"))),
        ("TIMESTAMP_FORMAT", 0),
    )
    add(
        "v2-timestamp-non-ascii-digits",
        "Arabic-Indic digits in the timestamp are TIMESTAMP_FORMAT (ASCII only).",
        lines(
            rehashed(
                0,
                lambda r: r.update(
                    timestamp="\u0662\u0660\u0662\u0666" + TIMESTAMPS[0][4:]
                ),
            )
        ),
        ("TIMESTAMP_FORMAT", 0),
    )
    add(
        "v2-policy-sha-trailing-newline",
        "A policy_sha256 ending in \\n is MALFORMED.",
        lines(rehashed(0, lambda r: r.update(policy_sha256=POLICY_SHA + "\n"))),
        ("MALFORMED", 0),
    )
    add(
        "v2-mode-invalid",
        "A mode outside enforce/observe is MALFORMED (step 5).",
        lines(rehashed(1, lambda r: r.update(mode="audit"))),
        ("MALFORMED", 1),
    )
    add(
        "v2-missing-and-extra-key",
        "A missing key wins over an extra key (step 2 before step 4).",
        lines(rehashed(1, lambda r: (r.pop("agent_id"), r.update(extra=1)))),
        ("MALFORMED", 1),
    )
    add(
        "v2-unknown-version-with-extra-key",
        "v: 3 wins over an extra key (step 3 before step 4).",
        lines(rehashed(1, lambda r: r.update(v=3, extra=1))),
        ("UNKNOWN_VERSION", 1),
    )
    add(
        "v2-chain-id-before-seq",
        "A foreign chain_id wins over a wrong seq (step 7 before step 8).",
        lines(rehashed(1, lambda r: r.update(chain_id="other-chain", seq=7))),
        ("CHAIN_ID_MISMATCH", 1),
    )
    float_v = lines(valid)
    float_v[0] = float_v[0].replace('"v":2}', '"v":2.0}')
    add(
        "v2-version-float",
        "v: 2.0 is not the integer 2 (UNKNOWN_VERSION).",
        float_v,
        ("UNKNOWN_VERSION", 0),
    )
    float_meta = lines(valid)
    float_meta[1] = float_meta[1].replace('"metadata":{"i":1}', '"metadata":{"i":1.5}')
    add(
        "v2-metadata-float",
        "A float in metadata is outside the JCS subset (MALFORMED).",
        float_meta,
        ("MALFORMED", 1),
    )
    nan_meta = lines(valid)
    nan_meta[1] = nan_meta[1].replace('"metadata":{"i":1}', '"metadata":{"i":NaN}')
    add(
        "v2-metadata-nan",
        "NaN is not JSON (INVALID_JSON).",
        nan_meta,
        ("INVALID_JSON", 1),
    )
    blank = lines(valid)
    add(
        "v2-blank-line",
        "An empty line after a v2 line is INVALID_JSON.",
        [blank[0], "", *blank[1:]],
        ("INVALID_JSON", 1),
    )
    mixed_lines = lines([v1a, v1b] + mixed_v2)
    add(
        "mixed-v1-blank-line-valid",
        "v1 rules skip empty lines before the first v2 line; seq counts records.",
        [mixed_lines[0], "", *mixed_lines[1:]],
        None,
    )
    separators = []
    prev = "0" * 64
    for seq, text in enumerate(["line\u2028sep", "next\u0085line"]):
        separators.append(
            _make_record(seq, prev, reason=text, metadata={"note": "\u2029"})
        )
        prev = separators[-1]["entry_hash"]
    add(
        "v2-valid-raw-separators",
        "U+2028, U+2029 and U+0085 stay raw in JCS; only \\n ends a line.",
        lines(separators),
        None,
    )

    after = _make_checkpoint(1, valid[1]["entry_hash"])
    add(
        "v2-valid-records-after-checkpoint",
        "A record after the last checkpoint verifies (known limit, SPEC §14.7).",
        lines(valid),
        None,
        [canonicalize(after).decode()],
        public_keys,
    )
    add(
        "v2-checkpoint-head-mismatch-intermediate",
        "Every checkpoint head is checked, not only the last one.",
        lines(valid),
        ("CHECKPOINT_HEAD_MISMATCH", 0),
        [
            canonicalize(_make_checkpoint(0, "b" * 64)).decode(),
            canonicalize(checkpoint).decode(),
        ],
        public_keys,
    )
    add(
        "v2-checkpoint-malformed-version",
        "A checkpoint with v: 3 is CHECKPOINT_MALFORMED (re-signed).",
        lines(valid),
        ("CHECKPOINT_MALFORMED", 2),
        [canonicalize(_make_checkpoint(2, valid[-1]["entry_hash"], v=3)).decode()],
        public_keys,
    )
    add(
        "v2-checkpoint-seq-decreases",
        "Checkpoint seq never decreases (CHECKPOINT_MALFORMED).",
        lines(valid),
        ("CHECKPOINT_MALFORMED", 1),
        [
            canonicalize(checkpoint).decode(),
            canonicalize(_make_checkpoint(1, valid[1]["entry_hash"])).decode(),
        ],
        public_keys,
    )
    alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"
    respelled = dict(checkpoint)
    respelled["sig"] = (
        respelled["sig"][:-1] + alphabet[alphabet.index(respelled["sig"][-1]) ^ 1]
    )
    add(
        "v2-checkpoint-sig-noncanonical",
        "A sig whose padding bits are not zero is CHECKPOINT_MALFORMED.",
        lines(valid),
        ("CHECKPOINT_MALFORMED", 2),
        [canonicalize(respelled).decode()],
        public_keys,
    )
    add(
        "v2-checkpoint-chain-id-mismatch",
        "A checkpoint for another chain is CHAIN_ID_MISMATCH (re-signed).",
        lines(valid),
        ("CHAIN_ID_MISMATCH", 2),
        [
            canonicalize(
                _make_checkpoint(2, valid[-1]["entry_hash"], chain_id="other-chain")
            ).decode()
        ],
        public_keys,
    )

    reordered = lines(valid)
    reordered[1] = json.dumps(
        dict(reversed(list(valid[1].items()))), separators=(",", ":")
    )
    add(
        "v2-line-not-canonical",
        "Same content in another key order is not JCS(record) (MALFORMED).",
        reordered,
        ("MALFORMED", 1),
    )
    crlf = lines(valid)
    add(
        "v2-line-crlf",
        "A trailing \\r makes the line differ from JCS(record) (MALFORMED).",
        [crlf[0], crlf[1] + "\r", crlf[2]],
        ("MALFORMED", 1),
    )
    add(
        "v2-chain-truncated-far",
        "CHAIN_TRUNCATED carries the record count, not the checkpoint seq.",
        lines(valid),
        ("CHAIN_TRUNCATED", 3),
        [canonicalize(_make_checkpoint(5, "e" * 64)).decode()],
        public_keys,
    )
    add(
        "v2-checkpoint-signature-invalid-mid",
        "Checkpoint failures carry the checkpoint seq, not a line index.",
        lines(valid),
        ("CHECKPOINT_SIGNATURE_INVALID", 0),
        [
            canonicalize(
                _make_checkpoint(0, valid[0]["entry_hash"], sig="A" * 86)
            ).decode()
        ],
        public_keys,
    )
    add(
        "v2-checkpoint-line-not-canonical",
        "A checkpoint line that is not JCS(checkpoint) is CHECKPOINT_MALFORMED.",
        lines(valid),
        ("CHECKPOINT_MALFORMED", 2),
        [json.dumps(checkpoint, sort_keys=True)],
        public_keys,
    )

    add(
        "v2-checkpoint-file-empty",
        "A given checkpoint file without lines protects nothing (CHECKPOINT_MISSING).",
        lines(valid),
        ("CHECKPOINT_MISSING", None),
        [],
        public_keys,
    )

    # --- parser limits must not change the result (SPEC 14.7, "Satırlar") ---
    base_line = lines(valid)[0]
    meta = '"metadata":{"i":0}'
    assert base_line.count('"v":2') == 1 and meta in base_line
    big = "1" + "0" * 5000  # longer than CPython's default int/str limit (4300)
    nest65 = "[" * 63 + "]" * 63  # record 1 + metadata 1 + 63 arrays = depth 65
    add(
        "v2-version-big-integer",
        "A 5001-digit v is an integer that is not 2: UNKNOWN_VERSION (step 3), "
        "never a parser error.",
        [base_line.replace('"v":2', '"v":' + big)],
        ("UNKNOWN_VERSION", 0),
    )
    add(
        "v2-metadata-big-integer",
        "A 5001-digit integer in metadata is outside the JCS range: MALFORMED (step 5).",
        [base_line.replace(meta, '"metadata":{"i":' + big + "}")],
        ("MALFORMED", 0),
    )
    add(
        "v2-nesting-65",
        "Nesting one level deeper than 64 is MALFORMED (step 5).",
        [base_line.replace(meta, '"metadata":{"i":' + nest65 + "}")],
        ("MALFORMED", 0),
    )
    add(
        "v2-version-3-with-nesting-65",
        "v = 3 (step 3) wins over nesting deeper than 64 (step 5).",
        [
            base_line.replace('"v":2', '"v":3').replace(
                meta, '"metadata":{"i":' + nest65 + "}"
            )
        ],
        ("UNKNOWN_VERSION", 0),
    )

    return {
        "format": 1,
        "suite": "audit-v2",
        "cases": cases,
    }


def build_jcs_cases() -> dict:
    # Expected outputs are written by hand as canonical text; the generator
    # never runs canonicalize() on them.
    rfc_input = (
        '{"\u20ac": "Euro Sign", "\\r": "Carriage Return", '
        '"\ufb33": "Hebrew Letter Dalet With Dagesh", "1": "One", '
        '"\U0001f600": "Emoji: Grinning Face", "\u0080": "Control", '
        '"\u00f6": "Latin Small Letter O With Diaeresis"}'
    )
    rfc_output = (
        '{"\\r":"Carriage Return","1":"One","\u0080":"Control",'
        '"\u00f6":"Latin Small Letter O With Diaeresis","\u20ac":"Euro Sign",'
        '"\U0001f600":"Emoji: Grinning Face",'
        '"\ufb33":"Hebrew Letter Dalet With Dagesh"}'
    )

    def ok(case_id, description, input_json, canonical):
        return {
            "id": case_id,
            "description": description,
            "input_json": input_json,
            "expected_hex": canonical.encode("utf-8").hex(),
        }

    def err(case_id, description, input_json, code):
        return {
            "id": case_id,
            "description": description,
            "input_json": input_json,
            "expected_error": code,
        }

    return {
        "format": 1,
        "suite": "jcs",
        "cases": [
            ok(
                "jcs-rfc-ordering",
                "RFC 8785 §3.2.3 UTF-16 key ordering example.",
                rfc_input,
                rfc_output,
            ),
            ok(
                "jcs-control-escape",
                "Control characters use short escapes or lowercase \\u00xx.",
                '{"k": "\\u0001\\u001f\\b\\t\\n\\f\\r"}',
                '{"k":"\\u0001\\u001f\\b\\t\\n\\f\\r"}',
            ),
            ok(
                "jcs-quote-backslash",
                "Quote and backslash escaping.",
                '{"k": "\\"\\\\"}',
                '{"k":"\\"\\\\"}',
            ),
            ok(
                "jcs-raw-non-ascii",
                "U+007F, U+2028 and U+2029 stay raw UTF-8; \\u escapes are decoded.",
                '{"k": "\\u007f\\u2028\\u2029\\u00e9"}',
                '{"k":"\u007f\u2028\u2029\u00e9"}',
            ),
            ok(
                "jcs-literals",
                "true/false/null serialization.",
                '{"c": null, "b": false, "a": true}',
                '{"a":true,"b":false,"c":null}',
            ),
            ok(
                "jcs-array-order",
                "Array order is preserved.",
                '{"a": [3, 1, 2]}',
                '{"a":[3,1,2]}',
            ),
            ok(
                "jcs-nested",
                "Nested objects are ordered at every level.",
                '{"b": {"z": 1, "a": 2}, "a": 3}',
                '{"a":3,"b":{"a":2,"z":1}}',
            ),
            ok(
                "jcs-integer-bounds",
                "Integers up to 2^53-1 in magnitude are written as digits.",
                '{"max": 9007199254740991, "min": -9007199254740991, "zero": 0}',
                '{"max":9007199254740991,"min":-9007199254740991,"zero":0}',
            ),
            err(
                "jcs-error-float",
                "Floats are unsupported.",
                '{"x":1.5}',
                "UNSUPPORTED_NUMBER",
            ),
            err(
                "jcs-error-integer-range",
                "2^53 is outside the integer range.",
                '{"x":9007199254740992}',
                "INTEGER_OUT_OF_RANGE",
            ),
            err(
                "jcs-error-depth",
                "More than 64 nested arrays/objects is an error.",
                "[" * 65 + "0" + "]" * 65,
                "NESTING_TOO_DEEP",
            ),
            err(
                "jcs-error-surrogate",
                "Lone surrogates are invalid.",
                '{"x":"\\ud800"}',
                "LONE_SURROGATE",
            ),
        ],
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="compare generated bytes with the files"
    )
    args = parser.parse_args()

    audit_dir = REPO / "conformance" / "audit"
    jcs_dir = REPO / "conformance" / "jcs"
    audit_file = audit_dir / "cases.json"
    jcs_file = jcs_dir / "cases.json"

    audit_bytes = (
        json.dumps(build_cases(), indent=2, ensure_ascii=False) + "\n"
    ).encode()
    jcs_bytes = (
        json.dumps(build_jcs_cases(), indent=2, ensure_ascii=False) + "\n"
    ).encode()

    if args.check:
        ok = True
        if audit_file.read_bytes() != audit_bytes:
            print(f"FAILED: {audit_file} differs")
            ok = False
        if jcs_file.read_bytes() != jcs_bytes:
            print(f"FAILED: {jcs_file} differs")
            ok = False
        return 0 if ok else 1

    audit_dir.mkdir(parents=True, exist_ok=True)
    jcs_dir.mkdir(parents=True, exist_ok=True)
    audit_file.write_bytes(audit_bytes)
    jcs_file.write_bytes(jcs_bytes)
    print(f"wrote {audit_file} ({len(build_cases()['cases'])} cases)")
    print(f"wrote {jcs_file} ({len(build_jcs_cases()['cases'])} cases)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
